// flow-typed signature: 92609e333a1987056500a1a8bbebee11
// flow-typed version: <<STUB>>/components_v0/flow_v0.32.0

/* eslint-disable */
/**
 * This is an autogenerated libdef stub for:
 *
 *   'fbjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'components' {
  declare module.exports: any;
}
